In [ ]:
import pandas as pd
import numpy as np
from WeeklyTrial import WeeklyTrial

In [ ]:
expiration = '2014-04-19'
last_trade_date = '2014-04-17'
execution = '2014-04-11'

In [ ]:
universe = ['DIA','IWM','QQQ','SPY']
leg_max = 10 # the maximum number of longs and shorts (for the initial iteration, since I am focused on a small universe this won't matter)
delta_long = 0.1 # delta of long strangles
delta_short = 0.1 # delta of short strangles
premium_budget = 2000

In [ ]:
wt = WeeklyTrial( expiration = expiration,
             last_trade_date = last_trade_date,
             execution = execution,
             universe = universe,
             leg_max = leg_max,
             delta_long = delta_long, # delta of long strangles
             delta_short = delta_short, # delta of short strangles
             premium_budget = premium_budget)
wt.calc_all()

2014-04-19

## `calc_chain_history()` & `calc_vol_premium_forecast`

In [ ]:
wt.chain_history

,underlying,expiration,trade_date,implied_forward,d2x,swap_rate_bid,swap_rate_ask,swap_rate_mid,ticker,week_num,week_start,week_end,close_to_close,vol_prem_forecast
2,QQQ,2014-04-19,2014-04-11,84.112,4,0.2634,0.2682,0.2658,QQQ,201,2014-04-07,2014-04-11,0.302300,-0.036500
3,SPY,2014-04-19,2014-04-11,181.519,4,0.1894,0.1924,0.1909,SPY,201,2014-04-07,2014-04-11,0.201741,-0.010841
1,IWM,2014-04-19,2014-04-11,110.305,4,0.2666,0.2734,0.2700,IWM,201,2014-04-07,2014-04-11,0.279479,-0.009479
0,DIA,2014-04-19,2014-04-11,159.987,4,0.1659,0.1739,0.1700,DIA,201,2014-04-07,2014-04-11,0.170015,-0.000015

In [ ]:
df_vol_forecasts = pd.read_csv('../data/close_to_close_forecasts.csv')

In [ ]:
(
df_vol_forecasts
    .query('week_end=="2014-04-11"')
    .query("ticker in ('DIA','IWM','QQQ','SPY')")
)

     ticker  week_num  week_start    week_end  close_to_close
201     DIA       201  2014-04-07  2014-04-11        0.170015
7353    IWM       201  2014-04-07  2014-04-11        0.279479
8247    QQQ       201  2014-04-07  2014-04-11        0.302300
9588    SPY       201  2014-04-07  2014-04-11        0.201741

## `calc_underlyings_to_trade()`

In [ ]:
wt.underlyings

,underlying,direction,expiration,execution,size,quantity,pnl_bid_ask,pnl_mid
0,QQQ,1,2014-04-19,2014-04-11,18.0,18.0,-704.16,-686.16
1,SPY,1,2014-04-19,2014-04-11,12.0,12.0,-831.60,-819.60
2,IWM,-1,2014-04-19,2014-04-11,14.0,-14.0,636.86,650.86
3,DIA,-1,2014-04-19,2014-04-11,16.0,-16.0,748.16,844.16

## `calc_all_otm_options()`

In [ ]:
for opt in wt.otm_options.values():
    display(opt)

,underlying,expiration,cp,strike,trade_date,upx,bid,ask,mid,implied_vol,delta,target_delta,abs_delta_diff
0,QQQ,2014-04-19,put,79.0,2014-04-11,84.11,0.11,0.12,0.115,0.3428,0.0703,0.1,0.0297
1,QQQ,2014-04-19,put,79.5,2014-04-11,84.11,0.13,0.14,0.135,0.3287,0.0834,0.1,0.0166
2,QQQ,2014-04-19,put,80.0,2014-04-11,84.11,0.15,0.16,0.155,0.3122,0.0978,0.1,0.0022
3,QQQ,2014-04-19,put,80.5,2014-04-11,84.11,0.19,0.21,0.200,0.3052,0.1229,0.1,0.0229
4,QQQ,2014-04-19,put,81.0,2014-04-11,84.11,0.25,0.26,0.255,0.2976,0.1529,0.1,0.0529
5,QQQ,2014-04-19,put,81.5,2014-04-11,84.11,0.31,0.33,0.320,0.2884,0.1877,0.1,0.0877
6,QQQ,2014-04-19,put,82.0,2014-04-11,84.11,0.40,0.42,0.410,0.2819,0.2315,0.1,0.1315
7,QQQ,2014-04-19,put,82.5,2014-04-11,84.11,0.51,0.53,0.520,0.2749,0.2823,0.1,0.1823
8,QQQ,2014-04-19,put,83.0,2014-04-11,84.11,0.65,0.67,0.660,0.2691,0.3411,0.1,0.2411
9,QQQ,2014-04-19,put,83.5,2014-04-11,84.11,0.82,0.84,0.830,0.2633,0.4064,0.1,0.3064
10,QQQ,2014-04-19,put,84.0,2014-04-11,84.11,1.03,1.04,1.035,0.2580,0.4772,0.1,0.3772
11,QQQ,2014-04-19,call,84.5,2014-04-11,84.11,0.89,0.90,0.895,0.2544,0.4492,0.1,0.3492
12,QQQ,2014-04-19,call,85.0,2014-04-11,84.11,0.68,0.70,0.690,0.2532,0.3770,0.1,0.2770
13,QQQ,2014-04-19,call,85.5,2014-04-11,84.11,0.50,0.51,0.505,0.2480,0.3057,0.1,0.2057
14,QQQ,2014-04-19,call,86.0,2014-04-11,84.11,0.36,0.37,0.365,0.2456,0.2414,0.1,0.1414
15,QQQ,2014-04-19,call,86.5,2014-04-11,84.11,0.24,0.25,0.245,0.2393,0.1805,0.1,0.0805
16,QQQ,2014-04-19,call,87.0,2014-04-11,84.11,0.17,0.18,0.175,0.2414,0.1368,0.1,0.0368
17,QQQ,2014-04-19,call,87.5,2014-04-11,84.11,0.12,0.13,0.125,0.2445,0.1027,0.1,0.0027
18,QQQ,2014-04-19,call,88.0,2014-04-11,84.11,0.08,0.09,0.085,0.2454,0.0741,0.1,0.0259
19,QQQ,2014-04-19,call,88.5,2014-04-11,84.11,0.06,0.07,0.065,0.2533,0.0573,0.1,0.0427
20,QQQ,2014-04-19,call,89.0,2014-04-11,84.11,0.04,0.05,0.045,0.2560,0.0413,0.1,0.0587
21,QQQ,2014-04-19,call,89.5,2014-04-11,84.11,0.03,0.04,0.035,0.2643,0.0323,0.1,0.0677

,underlying,expiration,cp,strike,trade_date,upx,bid,ask,mid,implied_vol,delta,target_delta,abs_delta_diff
0,SPY,2014-04-19,put,168.0,2014-04-11,181.51,0.05,0.07,0.060,0.3093,0.0224,0.1,0.0776
1,SPY,2014-04-19,put,169.0,2014-04-11,181.51,0.06,0.08,0.070,0.2966,0.0267,0.1,0.0733
2,SPY,2014-04-19,put,170.0,2014-04-11,181.51,0.08,0.09,0.085,0.2854,0.0328,0.1,0.0672
3,SPY,2014-04-19,put,171.0,2014-04-11,181.51,0.09,0.11,0.100,0.2722,0.0394,0.1,0.0606
4,SPY,2014-04-19,put,172.0,2014-04-11,181.51,0.12,0.13,0.125,0.2617,0.0494,0.1,0.0506
5,SPY,2014-04-19,put,173.0,2014-04-11,181.51,0.15,0.16,0.155,0.2503,0.0618,0.1,0.0382
6,SPY,2014-04-19,put,174.0,2014-04-11,181.51,0.19,0.20,0.195,0.2393,0.0781,0.1,0.0219
7,SPY,2014-04-19,put,175.0,2014-04-11,181.51,0.26,0.27,0.265,0.2325,0.1033,0.1,0.0033
8,SPY,2014-04-19,put,176.0,2014-04-11,181.51,0.34,0.36,0.350,0.2240,0.1339,0.1,0.0339
9,SPY,2014-04-19,put,176.5,2014-04-11,181.51,0.40,0.41,0.405,0.2201,0.1527,0.1,0.0527
10,SPY,2014-04-19,put,177.0,2014-04-11,181.51,0.46,0.47,0.465,0.2157,0.1733,0.1,0.0733
11,SPY,2014-04-19,put,177.5,2014-04-11,181.51,0.53,0.55,0.540,0.2122,0.1974,0.1,0.0974
12,SPY,2014-04-19,put,178.0,2014-04-11,181.51,0.61,0.63,0.620,0.2079,0.2235,0.1,0.1235
13,SPY,2014-04-19,put,178.5,2014-04-11,181.51,0.71,0.73,0.720,0.2046,0.2535,0.1,0.1535
14,SPY,2014-04-19,put,179.0,2014-04-11,181.51,0.82,0.84,0.830,0.2007,0.2859,0.1,0.1859
15,SPY,2014-04-19,put,179.5,2014-04-11,181.51,0.95,0.97,0.960,0.1975,0.3221,0.1,0.2221
16,SPY,2014-04-19,put,180.0,2014-04-11,181.51,1.09,1.10,1.095,0.1927,0.3601,0.1,0.2601
17,SPY,2014-04-19,put,180.5,2014-04-11,181.51,1.25,1.27,1.260,0.1892,0.4020,0.1,0.3020
18,SPY,2014-04-19,put,181.0,2014-04-11,181.51,1.43,1.45,1.440,0.1852,0.4466,0.1,0.3466
19,SPY,2014-04-19,put,181.5,2014-04-11,181.51,1.63,1.65,1.640,0.1808,0.4936,0.1,0.3936
20,SPY,2014-04-19,call,182.0,2014-04-11,181.51,1.38,1.39,1.385,0.1767,0.4571,0.1,0.3571
21,SPY,2014-04-19,call,182.5,2014-04-11,181.51,1.13,1.13,1.130,0.1718,0.4059,0.1,0.3059
22,SPY,2014-04-19,call,183.0,2014-04-11,181.51,0.90,0.92,0.910,0.1679,0.3544,0.1,0.2544
23,SPY,2014-04-19,call,183.5,2014-04-11,181.51,0.72,0.73,0.725,0.1650,0.3044,0.1,0.2044
24,SPY,2014-04-19,call,184.0,2014-04-11,181.51,0.55,0.56,0.555,0.1606,0.2544,0.1,0.1544
25,SPY,2014-04-19,call,184.5,2014-04-11,181.51,0.41,0.42,0.415,0.1567,0.2075,0.1,0.1075
26,SPY,2014-04-19,call,185.0,2014-04-11,181.51,0.31,0.32,0.315,0.1552,0.1681,0.1,0.0681
27,SPY,2014-04-19,call,185.5,2014-04-11,181.51,0.22,0.23,0.225,0.1518,0.1303,0.1,0.0303
28,SPY,2014-04-19,call,186.0,2014-04-11,181.51,0.16,0.17,0.165,0.1509,0.1015,0.1,0.0015
29,SPY,2014-04-19,call,186.5,2014-04-11,181.51,0.12,0.13,0.125,0.1519,0.0800,0.1,0.0200
30,SPY,2014-04-19,call,187.0,2014-04-11,181.51,0.09,0.10,0.095,0.1533,0.0629,0.1,0.0371
31,SPY,2014-04-19,call,187.5,2014-04-11,181.51,0.06,0.07,0.065,0.1517,0.0458,0.1,0.0542
32,SPY,2014-04-19,call,188.0,2014-04-11,181.51,0.05,0.06,0.055,0.1566,0.0385,0.1,0.0615
33,SPY,2014-04-19,call,188.5,2014-04-11,181.51,0.03,0.04,0.035,0.1538,0.0263,0.1,0.0737

,underlying,expiration,cp,strike,trade_date,upx,bid,ask,mid,implied_vol,delta,target_delta,abs_delta_diff
0,IWM,2014-04-19,put,98.0,2014-04-11,110.41,0.04,0.05,0.045,0.4588,0.0190,0.1,0.0810
1,IWM,2014-04-19,put,99.0,2014-04-11,110.41,0.05,0.06,0.055,0.4386,0.0236,0.1,0.0764
2,IWM,2014-04-19,put,100.0,2014-04-11,110.41,0.06,0.07,0.065,0.4154,0.0287,0.1,0.0713
3,IWM,2014-04-19,put,101.0,2014-04-11,110.41,0.07,0.08,0.075,0.3898,0.0345,0.1,0.0655
4,IWM,2014-04-19,put,102.0,2014-04-11,110.41,0.09,0.10,0.095,0.3699,0.0443,0.1,0.0557
5,IWM,2014-04-19,put,103.0,2014-04-11,110.41,0.11,0.12,0.115,0.3458,0.0554,0.1,0.0446
6,IWM,2014-04-19,put,104.0,2014-04-11,110.41,0.14,0.15,0.145,0.3235,0.0715,0.1,0.0285
7,IWM,2014-04-19,put,105.0,2014-04-11,110.41,0.20,0.21,0.205,0.3090,0.0993,0.1,0.0007
8,IWM,2014-04-19,put,106.0,2014-04-11,110.41,0.28,0.30,0.290,0.2944,0.1374,0.1,0.0374
9,IWM,2014-04-19,put,107.0,2014-04-11,110.41,0.41,0.44,0.425,0.2834,0.1922,0.1,0.0922
10,IWM,2014-04-19,put,107.5,2014-04-11,110.41,0.51,0.53,0.520,0.2797,0.2271,0.1,0.1271
11,IWM,2014-04-19,put,108.0,2014-04-11,110.41,0.63,0.64,0.635,0.2765,0.2664,0.1,0.1664
12,IWM,2014-04-19,put,108.5,2014-04-11,110.41,0.75,0.78,0.765,0.2724,0.3093,0.1,0.2093
13,IWM,2014-04-19,put,109.0,2014-04-11,110.41,0.91,0.93,0.920,0.2689,0.3563,0.1,0.2563
14,IWM,2014-04-19,put,109.5,2014-04-11,110.41,1.08,1.10,1.090,0.2638,0.4063,0.1,0.3063
15,IWM,2014-04-19,put,110.0,2014-04-11,110.41,1.27,1.30,1.285,0.2587,0.4597,0.1,0.3597
16,IWM,2014-04-19,call,110.5,2014-04-11,110.41,1.30,1.33,1.315,0.2542,0.4844,0.1,0.3844
17,IWM,2014-04-19,call,111.0,2014-04-11,110.41,1.04,1.08,1.060,0.2481,0.4265,0.1,0.3265
18,IWM,2014-04-19,call,111.5,2014-04-11,110.41,0.82,0.86,0.840,0.2430,0.3682,0.1,0.2682
19,IWM,2014-04-19,call,112.0,2014-04-11,110.41,0.64,0.67,0.655,0.2389,0.3115,0.1,0.2115
20,IWM,2014-04-19,call,112.5,2014-04-11,110.41,0.48,0.52,0.500,0.2351,0.2577,0.1,0.1577
21,IWM,2014-04-19,call,113.0,2014-04-11,110.41,0.37,0.39,0.380,0.2333,0.2100,0.1,0.1100
22,IWM,2014-04-19,call,113.5,2014-04-11,110.41,0.27,0.29,0.280,0.2307,0.1666,0.1,0.0666
23,IWM,2014-04-19,call,114.0,2014-04-11,110.41,0.20,0.21,0.205,0.2293,0.1301,0.1,0.0301
24,IWM,2014-04-19,call,114.5,2014-04-11,110.41,0.15,0.16,0.155,0.2312,0.1026,0.1,0.0026
25,IWM,2014-04-19,call,115.0,2014-04-11,110.41,0.11,0.12,0.115,0.2325,0.0795,0.1,0.0205
26,IWM,2014-04-19,call,115.5,2014-04-11,110.41,0.08,0.10,0.090,0.2371,0.0635,0.1,0.0365
27,IWM,2014-04-19,call,116.0,2014-04-11,110.41,0.06,0.08,0.070,0.2413,0.0504,0.1,0.0496
28,IWM,2014-04-19,call,116.5,2014-04-11,110.41,0.05,0.06,0.055,0.2460,0.0403,0.1,0.0597
29,IWM,2014-04-19,call,117.0,2014-04-11,110.41,0.04,0.05,0.045,0.2523,0.0330,0.1,0.0670
30,IWM,2014-04-19,call,117.5,2014-04-11,110.41,0.03,0.04,0.035,0.2563,0.0261,0.1,0.0739
31,IWM,2014-04-19,call,118.0,2014-04-11,110.41,0.02,0.03,0.025,0.2569,0.0194,0.1,0.0806

,underlying,expiration,cp,strike,trade_date,upx,bid,ask,mid,implied_vol,delta,target_delta,abs_delta_diff
0,DIA,2014-04-19,put,154.5,2014-04-11,160.02,0.15,0.24,0.195,0.2139,0.0954,0.1,0.0046
1,DIA,2014-04-19,put,155.0,2014-04-11,160.02,0.19,0.27,0.230,0.2086,0.1116,0.1,0.0116
2,DIA,2014-04-19,put,155.5,2014-04-11,160.02,0.22,0.32,0.270,0.2030,0.1303,0.1,0.0303
3,DIA,2014-04-19,put,156.0,2014-04-11,160.02,0.32,0.37,0.345,0.2030,0.1588,0.1,0.0588
4,DIA,2014-04-19,put,156.5,2014-04-11,160.02,0.39,0.44,0.415,0.1992,0.1866,0.1,0.0866
5,DIA,2014-04-19,put,157.0,2014-04-11,160.02,0.48,0.52,0.500,0.1957,0.2187,0.1,0.1187
6,DIA,2014-04-19,put,157.5,2014-04-11,160.02,0.58,0.62,0.600,0.1922,0.2549,0.1,0.1549
7,DIA,2014-04-19,put,158.0,2014-04-11,160.02,0.69,0.73,0.710,0.1875,0.2943,0.1,0.1943
8,DIA,2014-04-19,put,158.5,2014-04-11,160.02,0.81,0.87,0.840,0.1830,0.3385,0.1,0.2385
9,DIA,2014-04-19,put,159.0,2014-04-11,160.02,0.97,1.02,0.995,0.1790,0.3876,0.1,0.2876
10,DIA,2014-04-19,put,159.5,2014-04-11,160.02,1.15,1.20,1.175,0.1750,0.4407,0.1,0.3407
11,DIA,2014-04-19,call,160.0,2014-04-11,160.02,1.33,1.38,1.355,0.1693,0.5027,0.1,0.4027
12,DIA,2014-04-19,call,160.5,2014-04-11,160.02,1.06,1.11,1.085,0.1646,0.4427,0.1,0.3427
13,DIA,2014-04-19,call,161.0,2014-04-11,160.02,0.82,0.87,0.845,0.1597,0.3807,0.1,0.2807
14,DIA,2014-04-19,call,161.5,2014-04-11,160.02,0.62,0.67,0.645,0.1559,0.3194,0.1,0.2194
15,DIA,2014-04-19,call,162.0,2014-04-11,160.02,0.46,0.49,0.475,0.1517,0.2596,0.1,0.1596
16,DIA,2014-04-19,call,162.5,2014-04-11,160.02,0.32,0.37,0.345,0.1490,0.2059,0.1,0.1059
17,DIA,2014-04-19,call,163.0,2014-04-11,160.02,0.22,0.26,0.240,0.1458,0.1571,0.1,0.0571
18,DIA,2014-04-19,call,163.5,2014-04-11,160.02,0.15,0.18,0.165,0.1438,0.1171,0.1,0.0171
19,DIA,2014-04-19,call,164.0,2014-04-11,160.02,0.10,0.13,0.115,0.1436,0.0869,0.1,0.0131
20,DIA,2014-04-19,call,164.5,2014-04-11,160.02,0.06,0.09,0.075,0.1420,0.0611,0.1,0.0389
21,DIA,2014-04-19,call,165.0,2014-04-11,160.02,0.04,0.07,0.055,0.1446,0.0460,0.1,0.0540
22,DIA,2014-04-19,call,165.5,2014-04-11,160.02,0.03,0.05,0.040,0.1470,0.0344,0.1,0.0656
23,DIA,2014-04-19,call,166.0,2014-04-11,160.02,0.02,0.04,0.030,0.1503,0.0263,0.1,0.0737
24,DIA,2014-04-19,call,166.5,2014-04-11,160.02,0.01,0.03,0.020,0.1508,0.0183,0.1,0.0817

## `calc_strangle_trades()`

In [ ]:
for strangle in wt.strangle_trades.values():
    display(strangle)

,underlying,expiration,cp,strike,trade_date,upx,bid,ask,mid,implied_vol,delta,target_delta,abs_delta_diff,direction,size,quantity
0,QQQ,2014-04-19,put,80.0,2014-04-11,84.11,0.15,0.16,0.155,0.3122,0.0978,0.1,0.0022,1,18.0,18.0
1,QQQ,2014-04-19,call,87.5,2014-04-11,84.11,0.12,0.13,0.125,0.2445,0.1027,0.1,0.0027,1,18.0,18.0

,underlying,expiration,cp,strike,trade_date,upx,bid,ask,mid,implied_vol,delta,target_delta,abs_delta_diff,direction,size,quantity
0,SPY,2014-04-19,put,175.0,2014-04-11,181.51,0.26,0.27,0.265,0.2325,0.1033,0.1,0.0033,1,12.0,12.0
1,SPY,2014-04-19,call,186.0,2014-04-11,181.51,0.16,0.17,0.165,0.1509,0.1015,0.1,0.0015,1,12.0,12.0

,underlying,expiration,cp,strike,trade_date,upx,bid,ask,mid,implied_vol,delta,target_delta,abs_delta_diff,direction,size,quantity
0,IWM,2014-04-19,put,105.0,2014-04-11,110.41,0.20,0.21,0.205,0.3090,0.0993,0.1,0.0007,-1,14.0,-14.0
1,IWM,2014-04-19,call,114.5,2014-04-11,110.41,0.15,0.16,0.155,0.2312,0.1026,0.1,0.0026,-1,14.0,-14.0

,underlying,expiration,cp,strike,trade_date,upx,bid,ask,mid,implied_vol,delta,target_delta,abs_delta_diff,direction,size,quantity
0,DIA,2014-04-19,put,154.5,2014-04-11,160.02,0.15,0.24,0.195,0.2139,0.0954,0.1,0.0046,-1,16.0,-16.0
1,DIA,2014-04-19,call,164.0,2014-04-11,160.02,0.10,0.13,0.115,0.1436,0.0869,0.1,0.0131,-1,16.0,-16.0

## `calc_strangle_histories()`

In [ ]:
for hist in wt.strangle_histories.values():
    display(hist)

,underlying,expiration,cp,strike,trade_date,d2x,upx,bid,ask,mid,delta,sh_total_ask,lg_total_bid,spread,quantity,unit_pnl_bid_ask,unit_pnl_mid,dollar_pnl_bid_ask,dollar_pnl_mid
0,QQQ,2014-04-19,put,80.0,2014-04-11,4,84.1100,0.15,0.16,0.155,0.0978,0.0007,-0.0007,0.01,18.0,-0.0100,-0.0050,-18.00,-9.00
1,QQQ,2014-04-19,put,80.0,2014-04-14,3,84.7700,0.03,0.04,0.035,0.0326,0.0555,-0.0555,0.01,18.0,-0.0555,-0.0555,-99.90,-99.90
2,QQQ,2014-04-19,put,80.0,2014-04-15,2,85.0501,0.03,0.04,0.035,0.0308,-0.0091,0.0091,0.01,18.0,0.0091,0.0091,16.38,16.38
3,QQQ,2014-04-19,put,80.0,2014-04-16,1,86.1800,0.00,0.01,0.005,0.0000,-0.0048,0.0048,0.01,18.0,0.0048,0.0048,8.64,8.64
4,QQQ,2014-04-19,put,80.0,2014-04-17,0,86.2000,0.00,0.00,0.000,0.0000,0.0100,0.0000,0.00,18.0,0.0000,0.0000,0.00,0.00
0,QQQ,2014-04-19,call,87.5,2014-04-11,4,84.1100,0.12,0.13,0.125,0.1027,-0.0744,0.0744,0.01,18.0,-0.0100,-0.0050,-18.00,-9.00
1,QQQ,2014-04-19,call,87.5,2014-04-14,3,84.7700,0.08,0.09,0.085,0.0926,0.1078,-0.1078,0.01,18.0,-0.1078,-0.1078,-194.04,-194.04
2,QQQ,2014-04-19,call,87.5,2014-04-15,2,85.0501,0.08,0.09,0.085,0.1013,0.0259,-0.0259,0.01,18.0,-0.0259,-0.0259,-46.62,-46.62
3,QQQ,2014-04-19,call,87.5,2014-04-16,1,86.1800,0.03,0.04,0.035,0.0703,0.1645,-0.1645,0.01,18.0,-0.1645,-0.1645,-296.10,-296.10
4,QQQ,2014-04-19,call,87.5,2014-04-17,0,86.2000,0.00,0.00,0.000,0.0000,0.0414,-0.0314,0.00,18.0,-0.0314,-0.0314,-56.52,-56.52

,underlying,expiration,cp,strike,trade_date,d2x,upx,bid,ask,mid,delta,sh_total_ask,lg_total_bid,spread,quantity,unit_pnl_bid_ask,unit_pnl_mid,dollar_pnl_bid_ask,dollar_pnl_mid
0,SPY,2014-04-19,put,175.0,2014-04-11,4,181.5100,0.26,0.27,0.265,0.1033,0.0069,-0.0069,0.01,12.0,-0.0100,-0.0050,-12.00,-6.00
1,SPY,2014-04-19,put,175.0,2014-04-14,3,182.9401,0.04,0.05,0.045,0.0273,0.0723,-0.0723,0.01,12.0,-0.0723,-0.0723,-86.76,-86.76
2,SPY,2014-04-19,put,175.0,2014-04-15,2,184.2000,0.02,0.03,0.025,0.0155,-0.0144,0.0144,0.01,12.0,0.0144,0.0144,17.28,17.28
3,SPY,2014-04-19,put,175.0,2014-04-16,1,186.1250,0.00,0.01,0.005,0.0000,-0.0098,0.0098,0.01,12.0,0.0098,0.0098,11.76,11.76
4,SPY,2014-04-19,put,175.0,2014-04-17,0,186.3900,0.00,0.00,0.000,0.0000,0.0100,0.0000,0.00,12.0,0.0000,0.0000,0.00,0.00
0,SPY,2014-04-19,call,186.0,2014-04-11,4,181.5100,0.16,0.17,0.165,0.1015,-0.0946,0.0946,0.01,12.0,-0.0100,-0.0050,-12.00,-6.00
1,SPY,2014-04-19,call,186.0,2014-04-14,3,182.9401,0.14,0.15,0.145,0.1182,0.1652,-0.1652,0.01,12.0,-0.1652,-0.1652,-198.24,-198.24
2,SPY,2014-04-19,call,186.0,2014-04-15,2,184.2000,0.27,0.28,0.275,0.2254,0.0189,-0.0189,0.01,12.0,-0.0189,-0.0189,-22.68,-22.68
3,SPY,2014-04-19,call,186.0,2014-04-16,1,186.1250,0.51,0.52,0.515,0.4788,0.1939,-0.1939,0.01,12.0,-0.1939,-0.1939,-232.68,-232.68
4,SPY,2014-04-19,call,186.0,2014-04-17,0,186.3900,0.39,0.39,0.390,1.0000,0.2569,-0.2469,0.00,12.0,-0.2469,-0.2469,-296.28,-296.28

,underlying,expiration,cp,strike,trade_date,d2x,upx,bid,ask,mid,delta,sh_total_ask,lg_total_bid,spread,quantity,unit_pnl_bid_ask,unit_pnl_mid,dollar_pnl_bid_ask,dollar_pnl_mid
0,IWM,2014-04-19,put,105.0,2014-04-11,4,110.41,0.20,0.21,0.205,0.0993,0.0134,-0.0134,0.01,-14.0,-0.0100,-0.0050,-14.00,-7.00
1,IWM,2014-04-19,put,105.0,2014-04-14,3,110.72,0.05,0.06,0.055,0.0400,0.1192,-0.1192,0.01,-14.0,0.1192,0.1192,166.88,166.88
2,IWM,2014-04-19,put,105.0,2014-04-15,2,111.15,0.03,0.04,0.035,0.0270,0.0028,-0.0028,0.01,-14.0,0.0028,0.0028,3.92,3.92
3,IWM,2014-04-19,put,105.0,2014-04-16,1,112.36,0.00,0.02,0.010,0.0092,-0.0127,0.0027,0.02,-14.0,-0.0127,-0.0127,-17.78,-17.78
4,IWM,2014-04-19,put,105.0,2014-04-17,0,112.92,0.00,0.00,0.000,0.0000,0.0148,0.0052,0.00,-14.0,0.0148,0.0148,20.72,20.72
0,IWM,2014-04-19,call,114.5,2014-04-11,4,110.41,0.15,0.16,0.155,0.1026,-0.0965,0.0965,0.01,-14.0,-0.0100,-0.0050,-14.00,-7.00
1,IWM,2014-04-19,call,114.5,2014-04-14,3,110.72,0.07,0.09,0.080,0.0717,0.1018,-0.1118,0.02,-14.0,0.1018,0.1018,142.52,142.52
2,IWM,2014-04-19,call,114.5,2014-04-15,2,111.15,0.08,0.09,0.085,0.0819,0.0308,-0.0208,0.01,-14.0,0.0308,0.0308,43.12,43.12
3,IWM,2014-04-19,call,114.5,2014-04-16,1,112.36,0.02,0.04,0.030,0.0520,0.1491,-0.1591,0.02,-14.0,0.1491,0.1491,208.74,208.74
4,IWM,2014-04-19,call,114.5,2014-04-17,0,112.92,0.00,0.00,0.000,0.0000,0.0691,-0.0491,0.00,-14.0,0.0691,0.0691,96.74,96.74

,underlying,expiration,cp,strike,trade_date,d2x,upx,bid,ask,mid,delta,sh_total_ask,lg_total_bid,spread,quantity,unit_pnl_bid_ask,unit_pnl_mid,dollar_pnl_bid_ask,dollar_pnl_mid
0,DIA,2014-04-19,put,154.5,2014-04-11,4,160.02,0.15,0.24,0.195,0.0954,NaN,NaN,0.09,-16.0,-0.0900,-0.0450,-144.00,-72.00
1,DIA,2014-04-19,put,154.5,2014-04-14,3,161.45,0.01,0.06,0.035,0.0254,0.0436,-0.0036,0.05,-16.0,0.0436,0.0436,69.76,69.76
2,DIA,2014-04-19,put,154.5,2014-04-15,2,162.36,0.00,0.03,0.015,0.0121,0.0069,0.0131,0.03,-16.0,0.0069,0.0069,11.04,11.04
3,DIA,2014-04-19,put,154.5,2014-04-16,1,164.02,0.00,0.18,0.090,0.0402,-0.1701,0.0201,0.18,-16.0,-0.1701,-0.1701,-272.16,-272.16
4,DIA,2014-04-19,put,154.5,2014-04-17,0,163.75,0.00,0.00,0.000,0.0000,0.1909,-0.0109,0.00,-16.0,0.1909,0.1909,305.44,305.44
0,DIA,2014-04-19,call,164.0,2014-04-11,4,160.02,0.10,0.13,0.115,0.0869,-0.0936,0.1136,0.03,-16.0,-0.0300,-0.0150,-48.00,-24.00
1,DIA,2014-04-19,call,164.0,2014-04-14,3,161.45,0.09,0.11,0.100,0.1025,0.1443,-0.1343,0.02,-16.0,0.1443,0.1443,230.88,230.88
2,DIA,2014-04-19,call,164.0,2014-04-15,2,162.36,0.14,0.17,0.155,0.1694,0.0333,-0.0433,0.03,-16.0,0.0333,0.0333,53.28,53.28
3,DIA,2014-04-19,call,164.0,2014-04-16,1,164.02,0.39,0.44,0.415,0.4167,0.0112,-0.0312,0.05,-16.0,0.0112,0.0112,17.92,17.92
4,DIA,2014-04-19,call,164.0,2014-04-17,0,163.75,0.00,0.00,0.000,0.0000,0.3275,-0.2775,0.00,-16.0,0.3275,0.3275,524.00,524.00

In [ ]:
wt.underlyings

,underlying,direction,expiration,execution,size,quantity,pnl_bid_ask,pnl_mid
0,QQQ,1,2014-04-19,2014-04-11,18.0,18.0,-704.16,-686.16
1,SPY,1,2014-04-19,2014-04-11,12.0,12.0,-831.60,-819.60
2,IWM,-1,2014-04-19,2014-04-11,14.0,-14.0,636.86,650.86
3,DIA,-1,2014-04-19,2014-04-11,16.0,-16.0,748.16,844.16